### ISSUE TITLE
MANO param of cam0-cam3

### ISSUE THREAD

**Issue by binghui-z** [taeinkwon/h2oplayer#2]
Hi,  thank you for your nice work！ When I use this repo code, i can obtain correct hand-object in the view of camera4 . However,  when i  test the view of camera0-camera3,  error relative position between left and right hand occur， as image shows.

When testing camera0-camera3,  the code is same except corresponding path.

Please check whether there is a problem with the repo code or whether there is a problem with the mano parameters. Thank you! 
![view](https://user-images.githubusercontent.com/49152160/168758006-c59c7144-bea4-4ce0-b4f2-4892fe152515.png)

**Comment by taeinkwon** [comment]
Hi, 
When I test it (subject1/h1/0) with other camera paths, it works well from my side. (ex. I used cam1 instead of cam4 in the code)
One possibility is you are still using the old parameters. Did you download version 1.1? (ex. subject1_v1_1.tar.gz)

Could you also let me know which lines did you change to reproduce this problem?

**Comment by binghui-z** [comment]
Hi, thank you for your reply. I think I may have solved the problem.

When I test other cameras, I just need to change the path of the extrinsic parameters of the camera and keep the mano parameters corresponding to camera4, right?

**Comment by taeinkwon** [comment]
Hi,

For the test, I change the path of the extrinsic parameters and mano parameters together so that I can locate objects and hands in the right place in the world coordinate.
